apiVersion: v1
kind: PersistentVolume
metadata:
  name: archive-database
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/archive-database"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-database-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
