apiVersion: v1
kind: Service
metadata:
  name: archive-service
spec:
  type: NodePort
  selector:
    app: archive
  ports:
    - port: 9000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archive
  name: archive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archive
  template:
    metadata:
      labels:
        app: archive
    spec:
      containers:
        - name: openmina-archive
          image: vladsimplestakingcom/openmina-archive:0.2
          command: ["sh", "-c"]
          args:
            - openmina-archive --chain-id=3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e --path=/database --listen=/ip4/0.0.0.0/tcp/8302 --peer=/ip4/65.21.123.88/tcp/8302/p2p/12D3KooWLKSM9oHWU7qwL7Ci75wunkjXpRmK6j5xq527zGw554AF --http 9000 --head 3NLun5ymrVAEKBXTHunJo6SyZvnbUC63UJeijwsiru1mxzURzsdS
          env:
            - name: RUST_LOG
              value: info
          ports:
            - name: external-ip
              containerPort: 8302
              protocol: TCP
            - name: http
              containerPort: 9000
              protocol: TCP
          volumeMounts:
          - mountPath: /database
            name: openmina-archive-database
      volumes:
      - name: openmina-archive-database
